parameters:
#    ua_user.example.class: UA\UserBundle\Example

services:
#    ua_user.example:
#        class: %ua_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ua.twig.acme_extension:
        class: UA\UserBundle\Twig\UAExtension
        tags:
            - { name: twig.extension }
