<?php

namespace UA\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * gameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gameRepository extends EntityRepository
{
	public function getCountTeam() {
		$qb = $this ->createQueryBuilder('g');
		$qb			->join('g.teams', 't')
					->groupBy('t.game')
					->select(array('g.id', $qb->expr()->count('t.id')))
					->where('t.present = 1');

		$table = array();
		foreach ($qb->getQuery()->getResult() as $value) {
			$table[$value['id']] = $value[1];
		}

		return $table;
	}
}
