<?php

namespace UA\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * gameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gameRepository extends EntityRepository
{
}
