<?php

namespace UA\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
	public function getCount() {
		$qb = $this ->createQueryBuilder('a')
					->select('COUNT(a.id)');

		return $qb->getQuery()->getSingleScalarResult();
	}
}
