<?php

namespace UA\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getUsernamesByRegex($where) {
		$qb = $this ->createQueryBuilder('u');
		$qb 		->where($qb->expr()->like('u.username', ':term'))
					->setParameter('term', '%' . $where . '%');
		return $qb->getQuery()->getResult();
	}
}
