<?php

namespace UA\MatchBundle\Entity\Match;

use Doctrine\ORM\EntityRepository;

/**
 * matchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matchsRepository extends EntityRepository
{
	public function getWithPool($game) {
		$qb = $this	->createQueryBuilder('m');
		$qb			->where('m.game=' . $game)
					->andWhere($qb->expr()->eq('m.step', '?1'))
					->setParameter(1, 'pool')
					->join('m.teamA', 'p')
					->join('m.teamB', 'b')
					->select(array('m', 'b', 'p'))
					->orderBy('p.pool', 'ASC');
		return $qb->getQuery()->getResult();
	}

	public function getWithTeams($game) {
		$qb = $this	->createQueryBuilder('m');
		$qb			->where('m.game=' . $game)
					->andWhere($qb->expr()->neq('m.step', '?1'))
					->setParameter(1, 'pool')
					->join('m.teamA', 'p')
					->join('m.teamB', 'b')
					->select(array('m', 'b', 'p'))
					->orderBy('m.step', 'DESC');
		return $qb->getQuery()->getResult();
	}
}
