<?php

namespace UA\MatchBundle\Entity\Match;

use Doctrine\ORM\EntityRepository;

/**
 * matchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matchsRepository extends EntityRepository
{
	public function getWithPool($game) {
		$qb = $this	->createQueryBuilder('m')
					->where('m.game=' . $game)
					->join('m.teamA', 'p')
					->join('m.teamB', 'b')
					->select(array('m', 'b', 'p'))
					->orderBy('p.pool', 'ASC');
		return $qb->getQuery()->getResult();
	}
}
