<?php

namespace UA\MatchBundle\Entity\Match;

use Doctrine\ORM\EntityRepository;

/**
 * matchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matchsRepository extends EntityRepository
{
}
