<?php

namespace UA\MatchBundle\Entity\Match;

use Doctrine\ORM\EntityRepository;

/**
 * teamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamRepository extends EntityRepository
{
	public function getCount(array $where = null) {
		$qb = $this ->createQueryBuilder('t')
					->select('COUNT(t.id)');

		if($where)
		$qb 		->where($qb->expr()->in('t.game', $where));

		return $qb->getQuery()->getSingleScalarResult();
	}
}
